
CREATE TABLE TBL_TOKEN ( 
  ID BIGINT GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
  UID VARCHAR(32),
  TOKEN CHAR(16),
  AUTOLOGOUT INT,
  CREATE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);